// Supabase Edge Function: create-order
// Deploy with: supabase functions deploy create-order

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface OrderRequest {
  items: { name: string; quantity: number; price: number; eta_minutes?: number }[]
  total: number
  estimated_time: number
  status?: string
  payment_method?: string
  admin_id?: string
  canteen_id?: number
  user_id?: string
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    // Create Supabase client with the auth token from the request
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      {
        global: {
          headers: { Authorization: req.headers.get('Authorization')! },
        },
      }
    )

    // Parse request body
    const orderData: OrderRequest = await req.json()

    // Validate required fields
    if (!orderData.items || orderData.items.length === 0) {
      return new Response(
        JSON.stringify({ error: 'Items are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    if (!orderData.total || orderData.total <= 0) {
      return new Response(
        JSON.stringify({ error: 'Total must be greater than 0' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Prepare order insert data
    // Token number will be auto-generated by the database trigger
    const insertData = {
      items: orderData.items,
      total: orderData.total,
      estimated_time: orderData.estimated_time || 15,
      status: orderData.status || 'pending',
      payment_method: orderData.payment_method || 'online',
      admin_id: orderData.admin_id || null,
      canteen_id: orderData.canteen_id || null,
      user_id: orderData.user_id || null,
    }

    // Insert order into database
    // The database trigger will automatically generate the token_number
    const { data, error } = await supabaseClient
      .from('orders')
      .insert(insertData)
      .select()
      .single()

    if (error) {
      console.error('Database error:', error)
      return new Response(
        JSON.stringify({ error: error.message }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Return the created order
    return new Response(
      JSON.stringify({ order: data }),
      { status: 201, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (err) {
    console.error('Function error:', err)
    return new Response(
      JSON.stringify({ error: err.message || 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
